// The generated "Wiki annotations" label pack: every mob position the wiki states, written as
// ordinary map label files (`P x, y, z, r, g, b, size, label`) into the user mappacks folder, so
// the existing pack machinery — discovery, the Labels menu, shadowing — treats it like any pack
// a person installed. The map's gold dots and these labels are the same data; a pack label that
// disagrees with a dot (a stale hand-placed annotation) is exactly what this pack replaces.
import Foundation

@MainActor
enum MapAnnotations {
    /// The default pack name; the user can give any other at generation time.
    nonisolated static let defaultPackName = "EQC"
    /// Proof a directory is OURS to rewrite. A pack without it is somebody's data and is refused.
    nonisolated static let marker = ".eqc-generated"

    nonisolated static func dir(named name: String) -> URL {
        FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("EQCompanion/mappacks/\(name)", isDirectory: true)
    }

    struct Result { var zones = 0; var labels = 0 }

    enum GenerateError: LocalizedError {
        case badName
        case packExists(String)
        var errorDescription: String? {
            switch self {
            case .badName: return "Give the pack a plain name - letters, numbers, spaces, dashes."
            case .packExists(let n): return "A map pack named \u{201C}\(n)\u{201D} already exists and was not made by this app - pick another name rather than overwrite it."
            }
        }
    }

    nonisolated static func validName(_ name: String) -> String? {
        let n = name.trimmingCharacters(in: .whitespaces)
        guard !n.isEmpty, n.count <= 40, !n.hasPrefix("."),
              n.allSatisfy({ $0.isLetter || $0.isNumber || $0 == " " || $0 == "-" || $0 == "_" })
        else { return nil }
        return n
    }

    /// Write (or rewrite) the pack: one `<stem>_1.txt` per zone that has any placed wiki mob.
    /// Rewriting requires the marker — this app only ever replaces what it generated itself.
    @discardableResult
    static func generate(named rawName: String = MapAnnotations.defaultPackName, into override: URL? = nil) throws -> Result {
        guard let name = validName(rawName) else { throw GenerateError.badName }
        let dir = override ?? Self.dir(named: name)
        let fm = FileManager.default
        if fm.fileExists(atPath: dir.path) {
            guard fm.fileExists(atPath: dir.appendingPathComponent(marker).path) else {
                throw GenerateError.packExists(name)
            }
            try fm.removeItem(at: dir)
        }
        try fm.createDirectory(at: dir, withIntermediateDirectories: true)
        try Data("Generated by EQ Companion from the wiki mob positions. Safe to delete.\n".utf8)
            .write(to: dir.appendingPathComponent(marker))
        var out = Result()
        for z in GameData.shared.zones {
            var lines: [String] = []
            for row in MapPaneRows.mobRows(zoneName: z.name) where row.kind == .mob {
                for pin in row.pins {
                    // The game's label convention: underscores, shown as spaces. Gold, mid size.
                    let label = row.name.replacingOccurrences(of: ",", with: " ")
                        .replacingOccurrences(of: " ", with: "_")
                    lines.append(String(format: "P %.4f, %.4f, 0.0000, 217, 178, 95, 2, %@",
                                        pin.x, pin.y, label))
                }
            }
            guard !lines.isEmpty else { continue }
            let url = dir.appendingPathComponent("\(z.short)_1.txt")
            try (lines.joined(separator: "\n") + "\n").write(to: url, atomically: true, encoding: .utf8)
            out.zones += 1
            out.labels += lines.count
        }
        return out
    }
}
