// The generated "Wiki annotations" label pack: every mob position the wiki states, written as
// ordinary map label files (`P x, y, z, r, g, b, size, label`) into the user mappacks folder, so
// the existing pack machinery — discovery, the Labels menu, shadowing — treats it like any pack
// a person installed. The map's gold dots and these labels are the same data; a pack label that
// disagrees with a dot (a stale hand-placed annotation) is exactly what this pack replaces.
import Foundation

@MainActor
enum MapAnnotations {
    /// The default pack name; the user can give any other at generation time.
    nonisolated static let defaultPackName = "EQC"
    /// Proof a directory is OURS to rewrite. A pack without it is somebody's data and is refused.
    nonisolated static let marker = ".eqc-generated"

    /// The pack lives INSIDE the EverQuest install's own maps directory, as a subfolder — the
    /// same place a hand-installed pack goes, so the game's files and the pack sit side by side.
    nonisolated static func dir(named name: String, root: URL) -> URL {
        root.appendingPathComponent("maps/\(name)", isDirectory: true)
    }

    struct Result { var zones = 0; var labels = 0 }

    /// What to write. The wiki's own naming convention is the classifier: a NAMED (or rare) mob
    /// is capitalized ("Skeleton Lrodd"); a common spawn is lowercase ("a froglok sentry").
    struct Filter {
        /// Always-on half: the named and rare mobs.
        var named = true
        /// The fluff — every lowercase-named common spawn.
        var common = false

        func keeps(_ name: String) -> Bool {
            let isCommon = name.first.map { $0.isLowercase } ?? true
            return isCommon ? common : named
        }
    }

    enum GenerateError: LocalizedError {
        case badName
        case noInstall
        case packExists(String)
        var errorDescription: String? {
            switch self {
            case .badName: return "Give the pack a plain name - letters, numbers, spaces, dashes."
            case .noInstall: return "No EverQuest folder is set - point Preferences \u{2192} Game at your install first."
            case .packExists(let n): return "A map pack named \u{201C}\(n)\u{201D} already exists and was not made by this app - pick another name rather than overwrite it."
            }
        }
    }

    nonisolated static func validName(_ name: String) -> String? {
        let n = name.trimmingCharacters(in: .whitespaces)
        guard !n.isEmpty, n.count <= 40, !n.hasPrefix("."),
              n.allSatisfy({ $0.isLetter || $0.isNumber || $0 == " " || $0 == "-" || $0 == "_" })
        else { return nil }
        return n
    }

    /// Write (or rewrite) the pack: one `<stem>_1.txt` per zone that has any placed wiki mob.
    /// Rewriting requires the marker — this app only ever replaces what it generated itself.
    @discardableResult
    static func generate(named rawName: String = MapAnnotations.defaultPackName, root: URL? = nil, into override: URL? = nil, filter: Filter = Filter()) throws -> Result {
        guard let name = validName(rawName) else { throw GenerateError.badName }
        let dir: URL
        if let override { dir = override }
        else if let root { dir = Self.dir(named: name, root: root) }
        else { throw GenerateError.noInstall }
        let fm = FileManager.default
        if fm.fileExists(atPath: dir.path) {
            guard fm.fileExists(atPath: dir.appendingPathComponent(marker).path) else {
                throw GenerateError.packExists(name)
            }
            try fm.removeItem(at: dir)
        }
        try fm.createDirectory(at: dir, withIntermediateDirectories: true)
        try Data("Generated by EQ Companion from the wiki mob positions. Safe to delete.\n".utf8)
            .write(to: dir.appendingPathComponent(marker))
        var out = Result()
        for z in GameData.shared.zones {
            var lines: [String] = []
            for row in MapPaneRows.mobRows(zoneName: z.name) where row.kind == .mob && filter.keeps(row.name) {
                for pin in row.pins {
                    // The game's label convention: underscores, shown as spaces. A strong red:
                    // readable on the game's parchment map AND on the companion's dark one —
                    // gold disappears into parchment.
                    let label = row.name.replacingOccurrences(of: ",", with: " ")
                        .replacingOccurrences(of: " ", with: "_")
                    lines.append(String(format: "P %.4f, %.4f, 0.0000, 200, 40, 40, 2, %@",
                                        pin.x, pin.y, label))
                }
            }
            guard !lines.isEmpty else { continue }
            let url = dir.appendingPathComponent("\(z.short)_1.txt")
            try (lines.joined(separator: "\n") + "\n").write(to: url, atomically: true, encoding: .utf8)
            out.zones += 1
            out.labels += lines.count
        }
        return out
    }
}
