// swift-tools-version: 6.0
// EQ Companion for macOS — a self-contained native app. The engine that the Windows app runs as a
// Rust process is ported here, target for crate:
//
//   EQData            the committed game knowledge (JSON) and wiki images, as bundle resources
//   EQLog             the log parser: bytes in, canonical events out          (eqlog)
//   EQFold            the twenty modules + the combat engine                  (fold)
//   EQKnowledge       item / mob / quest corpora lookups                       (knowledge)
//   EQEngine          views, ops, the world, the in-process transport          (engined)
//   EQCompanionCore   the client half (subscriptions, epoch law) — unchanged
//   EQCompanion       the SwiftUI app (and its updater, Sparkle — the only outside dependency)
//
// Every ported piece is verified against goldens the Rust engine produced (`Goldens/`, generated by
// `scripts/gen-goldens.sh`): the parser byte-for-byte, the fold deep-equal.
import PackageDescription

let v5: [SwiftSetting] = [.swiftLanguageMode(.v5)]

let package = Package(
    name: "EQCompanion",
    platforms: [.macOS(.v14)],
    products: [
        .executable(name: "EQCompanion", targets: ["EQCompanion"]),
        // Libraries, so the dev tools in Tools/ (eqtool, eqbench) can depend on this package.
        .library(name: "EQCompanionCore", targets: ["EQCompanionCore"]),
        .library(name: "EQLog", targets: ["EQLog"]),
        .library(name: "EQFold", targets: ["EQFold"]),
        .library(name: "EQKnowledge", targets: ["EQKnowledge"]),
        .library(name: "EQEngine", targets: ["EQEngine"]),
        .library(name: "EQData", targets: ["EQData"])
    ],
    // The one outside dependency: Sparkle, the app's updater (appcast check, EdDSA-verified
    // download, install and relaunch). Only the app links it — the engine and the tools do not.
    dependencies: [
        .package(url: "https://github.com/sparkle-project/Sparkle", from: "2.10.0")
    ],
    targets: [
        .target(name: "EQData", path: "Sources/EQData",
                resources: [.copy("data"), .copy("wiki-images")], swiftSettings: v5),
        .target(name: "EQLog", dependencies: ["EQData"], path: "Sources/EQLog", swiftSettings: v5),
        .target(name: "EQFold", dependencies: ["EQLog", "EQData", "EQCompanionCore"], path: "Sources/EQFold", swiftSettings: v5),
        .target(name: "EQKnowledge", dependencies: ["EQData", "EQCompanionCore", "EQFold", "EQLog"], path: "Sources/EQKnowledge", swiftSettings: v5),
        .target(name: "EQEngine", dependencies: ["EQLog", "EQFold", "EQKnowledge", "EQCompanionCore"], path: "Sources/EQEngine", swiftSettings: v5),
        .target(name: "EQCompanionCore", path: "Sources/EQCompanionCore", swiftSettings: v5),
        .executableTarget(name: "EQCompanion",
                          dependencies: ["EQCompanionCore", "EQEngine", "EQData",
                                         .product(name: "Sparkle", package: "Sparkle")],
                          path: "Sources/EQCompanion", swiftSettings: v5),
        .testTarget(name: "EQLogTests", dependencies: ["EQLog", "EQCompanionCore"], path: "Tests/EQLogTests", swiftSettings: v5),
        .testTarget(name: "EQEngineTests", dependencies: ["EQEngine", "EQFold", "EQLog", "EQKnowledge", "EQCompanionCore"], path: "Tests/EQEngineTests", swiftSettings: v5),
        .testTarget(name: "EQFoldTests", dependencies: ["EQFold", "EQLog", "EQCompanionCore"], path: "Tests/EQFoldTests", swiftSettings: v5),
        .testTarget(name: "EQCompanionTests", dependencies: ["EQCompanion", "EQCompanionCore"],
                    path: "Tests/EQCompanionTests", resources: [.copy("Fixtures")], swiftSettings: v5),
        .testTarget(name: "EQCompanionCoreTests", dependencies: ["EQCompanionCore"], path: "Tests/EQCompanionCoreTests", swiftSettings: v5)
    ]
)
